spring:
  application:
    name: service-feign
server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
info:
  application.name: ${spring.application.name}
  company.name: www.camelot.com
  build: 
    version: $project.version$
    artifactId: $project.artifactId$  
feign.hystrix.enabled: true  #开启熔断器功能    D版本之后默认关闭hystrix  