server.port: 8771
spring: 
  zipkin: 
    base-url: http://localhost:8769
  application: 
    name: service-miya
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
info:
  application.name: ${spring.application.name}
  company.name: www.camelot.com
  build: 
    version: $project.version$
    artifactId: $project.artifactId$