server.port: 8766
spring.application.name: service-zuul
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
      
#zuul.routes.service-feign: /feign/**
#zuul.routes.service-ribbon: /ribbon/**
zuul.ignored-services: service-feign,service-ribbon
zuul.routes.service-client1.path: /feign/**
zuul.routes.service-client1.serviceId: service-feign
zuul.routes.service-client2.path: /ribbon/**
zuul.routes.service-client2.serviceId: service-ribbon
      
zuul.max.host.connections: 500
zuul.host.socket-timeout-millis: 60000
zuul.host.connect-timeout-millis: 60000

info.application.name: ${spring.application.name}
info.company.name: www.camelot.com
info.build.version: $project.version$
info.build.artifactId: $project.artifactId$ 
      
ribbon.ReadTimeout: 10000
ribbon.ConnectTimeout: 10000
ribbon.MaxAutoRetries: 0
ribbon.MaxAutoRetriesNextServer: 1

hystrix.command.default.execution.timeout.enabled: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000      
