server.port: 8764
spring.application.name: service-ribbon

#security.basic.enabled: true  # 开启安全控制
#security.user.name: root  # 用户名
#security.user.password: root  # 密码  

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
eureka.client.eurekaServerTotalConnections: 2 #允许多少个server连接client   
eureka.instance.prefer-ip-address: true
#eureka.instance.lease-renewal-interval-in-seconds: 1 //租期更新时间间隔（默认30秒）
#eureka.instance.lease-expiration-duration-in-seconds: 2  //租期到期时间（默认90秒）
eureka.healthcheck.enabled: true  #//开启健康检查（需要spring-boot-starter-actuator依赖）

info.application.name: ${spring.application.name}
info.company.name: www.rails.com
info.build.version: $project.version$
info.build.artifactId: $project.artifactId$
 
self.ribbon-rule.ribbon.NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#hystrix.command.default.execution.timeout.enabled: false 