spring:
  application:
    name: service-ribbon
server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
info:
  application.name: ${spring.application.name}
  company.name: www.camelot.com
  build: 
    version: $project.version$
    artifactId: $project.artifactId$  
self.ribbon-rule: 
  ribbon: 
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  