spring:
  application:
    name: service-zipkin
server:
  port: 8769
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
info:
  application.name: ${spring.application.name}
  company.name: www.camelot.com
  build: 
    version: $project.version$
    artifactId: $project.artifactId$  